// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEU07LY6eyXlcfgKBUIak3nW5i0kWyB_Y',
    appId: '1:324218061639:web:fb7fba96eadcd661280262',
    messagingSenderId: '324218061639',
    projectId: 'quizapp-41020',
    authDomain: 'quizapp-41020.firebaseapp.com',
    storageBucket: 'quizapp-41020.appspot.com',
    measurementId: 'G-BB2M7WW7CT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAByZMgSQlzQ9A6JjMwRLNJ_24i2I7R1LU',
    appId: '1:324218061639:android:1e38ef34247dcf0f280262',
    messagingSenderId: '324218061639',
    projectId: 'quizapp-41020',
    storageBucket: 'quizapp-41020.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUa_4sZe8H2kM6fZ2ZWy18qdnaynG7Vi4',
    appId: '1:324218061639:ios:74d69615f9979b99280262',
    messagingSenderId: '324218061639',
    projectId: 'quizapp-41020',
    storageBucket: 'quizapp-41020.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUa_4sZe8H2kM6fZ2ZWy18qdnaynG7Vi4',
    appId: '1:324218061639:ios:74d69615f9979b99280262',
    messagingSenderId: '324218061639',
    projectId: 'quizapp-41020',
    storageBucket: 'quizapp-41020.appspot.com',
    iosBundleId: 'com.example.quizapp',
  );
}
